version: "2.1"


services:
  database:
    image: mysql:8.0
    container_name: mysql_global
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main_base
    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

