version: "2.1"

services:
  webapp:
    build: ./webapp
    container_name: flask_app
    restart: always
    environment:
      DATABASE: ${DATABASE}
      TABLE: ${MAIN_TABLE}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./logs:/var/log/webapp
    ports:
      - 8888:5000
    links:
      - database
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: flask_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MAIN_TABLE: ${MAIN_TABLE}
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: 0.0.0.0

    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

